<?php


namespace api\forms\account;

use api\components\BaseForm;
use common\models\UserContact;

class UserContactForm extends BaseForm
{

    public $relationship;
    public $phoneNumber;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['relationship', 'phoneNumber'], 'required'],
            ['phoneNumber', 'trim'],
        ];
    }

    public function validateContactPerson($attribute, $params = [])
    {
        $count = UserContact::find()->where([
            'userId'      => \Yii::$app->user->id,
            'phoneNumber' => $this->phoneNumber
        ])->count();
        if ($count > 0) {
            $this->addError($attribute, \Yii::t('app', '{attribute} "{value}" has already been taken.', [
                'attribute' => $attribute,
                'value'     => $this->phoneNumber
            ]));
        }
    }


    public function submit()
    {
        $userContact               = new UserContact();
        $userContact->userId       = \Yii::$app->user->id;
        $userContact->relationship = $this->relationship;
        $userContact->phoneNumber  = $this->phoneNumber;
        return $userContact->save();
    }

    public function response()
    {
        return [];
    }

}