<?php
/**
 * Created by PhpStorm.
 * User: Nadzif Glovory
 * Date: 11/24/2019
 * Time: 10:39 PM
 */

namespace common\widgets;


use kartik\depdrop\DepDrop as KartikDepDrop;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\JsExpression;

class DepDrop extends KartikDepDrop
{
    public $select2Options = [
        'theme'         => Select2::THEME_BOOTSTRAP,
        'pluginOptions' => [
            'closeOnSelect' => true
        ],
    ];

    public $ajaxUrl;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->ajaxUrl) {
            $this->select2Options['pluginOptions']= ArrayHelper::merge($this->select2Options['pluginOptions'], [
                'allowClear'         => true,
                'minimumInputLength' => 3,
                'language'           => [
                    'errorLoading' => new JsExpression("function () { return 'Waiting for results...'; }"),
                ],
                'ajax'               => [
                    'url'      => Url::to($this->ajaxUrl),
                    'dataType' => 'json',
                    'data'     => new JsExpression('function(params) { return {search:params.term}; }')
                ],
//                'escapeMarkup'       => new JsExpression('function (markup) { return markup; }'),
//                'templateResult'     => new JsExpression('function (data) { return data.text; }'),
//                'templateSelection'  => new JsExpression('function (data) { return data.text; }'),
            ]);
        }
    }
}